config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'admin' => 'rails_admin/main#dashboard'
  
  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users
  
  get 'signup_for_drivers' => 'drivers#new'
  resources :drivers
  
  
  get 'packages' => 'packages#new'
  resources :packages
  
  get 'jobs' => 'jobs#show'
  resources :jobs

end

app/models/admin.rb
class Admin < ActiveRecord::Base
    before_save { self.email = email.downcase }
    validates :name,  presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                format: { with: VALID_EMAIL_REGEX },
                uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
end

app/models/driver.rb
class Driver < ActiveRecord::Base
    before_save { self.email = email.downcase }
    validates :name, presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                     format: { with: VALID_EMAIL_REGEX },
                     uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
    
    def Driver.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
    end
    
    has_many :packages
end

app/models/package.rb
class Package < ActiveRecord::Base
    before_save { self.email = email.downcase }
    validates :name, presence: true, length: { maximum:50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                     format: { with: VALID_EMAIL_REGEX }
                     # uniqueness: { case_sensitive: false }
    validates :phone, presence: true, length: { maximum: 10 }
    validates :address, presence: true, length: { maximum: 100 }
    validates :pickup_time, presence: true
    validates :package_type, presence: true
    validates :weight, presence: true
    
    belongs_to :driver, :foreign_key => "driver_id"
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
             format: { with: VALID_EMAIL_REGEX },
             uniqueness: { case_sensitive: false }
             
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController
  def index
    @driver = Driver.find(params[:id])
    @packages = Package.all.include(@driver.id)
  end
  
  def new
    @driver = Driver.new
  end
  
  def show
    @driver = Driver.find(params[:id])
    @packages = Package.all
  end
  
  def create
    @driver = Driver.new(driver_params)
    if @driver.save
      log_in @driver
      redirect_to @driver
    else
      render 'new'
    end
  end
  
  private

    def driver_params
      params.require(:driver).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

app/controllers/packages_controller.rb
class PackagesController < ApplicationController
  def new
    @package = Package.new
  end
  
  def show
    @package = Package.find(params[:id])
  end
  
  def create
    @package = Package.new(package_params)
    if @package.save
      redirect_to @package
    else
      render 'new'
    end
  end
  
  private

    def package_params
      params.require(:package).permit(:name, :email, :phone, :address,
                                      :pickup_time, :package_type, :weight)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
      user = User.find_by(email: params[:session][:email].downcase)
      driver = Driver.find_by(email: params[:session][:email].downcase)
      admin_user = Admin.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    elsif driver && driver.authenticate(params[:session][:password])
      log_in driver
      redirect_to driver
    elsif admin_user && admin_user.authenticate(params[:session][:password])
      redirect_to admin_path
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def create
    @user = User.new(user_params)    
    if @user.save
      log_in @user
      redirect_to @user
    else
      render 'new'
    end
  end
  
  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = "Delivery"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/helpers/packages_helper.rb
module PackagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end
  
  def log_in(driver)
    session[:driver_id] = driver.id
  end
  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def current_driver
    @current_driver ||= Driver.find_by(id: session[:driver_id])
  end
  
  def logged_in?
    !current_user.nil?
    !current_driver.nil?
  end
  
  def log_out
    session.delete(:user_id)
    session.delete(:driver_id)
    @current_user = nil
    @current_driver = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/drivers/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up for driver</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@driver) do |f| %>
    <%= render 'shared/error_messages_for_driver' %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/drivers/show.html.erb
<p><%= @driver.name %>, <%= @driver.email %></p>


<h3>List of Jobs</h3>
<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Phone</th>
            <th>Address</th>
            <th>Pickup time</th>
            <th>Package type</th>
            <th>Weight</th>
            <th>Status</th>
         </tr>
    </thead>
    <tbody>
    <% @packages.each do |p| %>
        <% if @driver.id == p.driver_id %>
            <tr>
                <td><%= p.name %></td>
                <td><%= p.email %></td>
                <td><%= p.phone %></td>
                <td><%= p.address %></td>
                <td><%= p.pickup_time %></td>
                <td><%= p.package_type %></td>
                <td><%= p.weight %></td>
                <td><%= select_tag '#', options_for_select(["picked up", "delivered", "not delivered", "returned"]), :style => "width:120px" %></td>
            </tr>
        <% end %> 
    <% end %>
    </tbody>
</table>

 

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    QUT
  </small>
  <nav>
    <ul>
      <%= link_to "Sign up for driver", signup_for_drivers_path %>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Delivery", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", '#' %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <% if logged_in? == current_user %>
                 <li><%= link_to "Profile", current_user %></li>
              <% else %>
                 <li><%= link_to "Profile", current_driver %></li>
              <% end %>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_error_messages_for_driver.html.erb
<% if @driver.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@driver.errors.count, "error") %>.
    </div>
    <ul>
    <% @driver.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_error_messages_for_package.html.erb
<% if @package.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@package.errors.count, "error") %>.
    </div>
    <ul>
    <% @package.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  The <a href="http://www.railstutorial.org/"><em>Ruby on Rails
  Tutorial</em></a> is a
  <a href="http://railstutorial.jp">book</a> and
  <a href="http://screencasts.railstutorial.org/">screencast series</a>
  to teach web development with
  <a href="http://rubyonrails.org/">Ruby on Rails</a>.
  This is the sample application for the tutorial.
</p>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>

<div class="center jumbotron">
  <h1>Delivery Service</h1>

  <h2>
    test
  </h2>

  <%= link_to "Sign up", signup_path, class: "btn btn-lg btn-primary" %>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<p><%= @user.name %>, <%= @user.email %></p>

<%= link_to "Package", packages_path, class: "btn btn-lg btn-primary" %>